### ISSUE TITLE
Doesn't work when downloaded from zip or not with --recursive

### ISSUE THREAD

**Issue by Raysnoth** [Seluj78/42PyChecker#97]
submodules aren't fetched

**Comment by Seluj78** [comment]
One possible solution to this problem would be to handle it like `42FileChecker` handles it. 
It doesnt have submodules and instead clones the repositories when needed.

This might be a better solution even though it might introduce a little more code and some bugs, It would make things easier to add, remove and change repositories or monitor them and see if they got updated
